version: "3.9"
services:
  ilo.testing.db:
    image: mariadb:latest
    tmpfs:
      - /var/lib/mysql:rw
    ports:
      - '4306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "test_pass"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "test_pass"
      MYSQL_DATABASE: "test_db"
