apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-backend-beanstalkd-deployment
  namespace: live-namespace
  labels:
    name: live-backend-beanstalkd-deployment
    app: live-backend-webapp
    tier: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      name: live-backend-beanstalkd-pod
      app: live-backend-webapp
      tier: backend

  template:
    metadata:
      name: live-backend-beanstalkd-pod
      labels:
        name: live-backend-beanstalkd-pod
        app: live-backend-webapp
        tier: backend
    spec:
      containers:
        - name: loyalty-backend-beanstalkd-live
          image: c3n7/lunar_store_beanstalkd:$VERSION
          ports:
            - containerPort: 11300
---
apiVersion: v1
kind: Service
metadata:
  name: live-backend-beanstalkd-service
  namespace: live-namespace
  labels:
    name: live-backend-beanstalkd-service
    app: live-backend-webapp
    tier: backend

spec:
  type: ClusterIP
  ports:
    - port: 11300
      targetPort: 11300
  selector:
    name: live-backend-beanstalkd-pod
    app: live-backend-webapp
    tier: backend
